# Generated by Django 5.2 on 2025-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('continut', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(upload_to='imagini_galerie/')),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntrebareBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrebare', models.CharField(max_length=300)),
                ('variante', models.TextField(help_text='JSON')),
            ],
        ),
        migrations.CreateModel(
            name='MesajContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subiect', models.CharField(max_length=200)),
                ('numar_pisici', models.PositiveIntegerField(default=0)),
                ('mesaj', models.TextField()),
                ('abonat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostareBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('poza', models.ImageField(upload_to='imagini_blog/')),
                ('descriere', models.TextField()),
                ('continut_html', models.TextField()),
                ('etichete', models.CharField(max_length=300)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
