# Generated by Django 5.2 on 2025-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_despre_elementgalerie_intrebarebot_mesajcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentariu', models.TextField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-data_creare'],
            },
        ),
        migrations.AlterField(
            model_name='postareblog',
            name='poza',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
